"""PCAN-Explorer-compatible .trc CAN capture logging (added 2026-08-01, user
request: "can we add a data logger. must keep the .trc format. I want to log
so that we can check and confirm things as we test.").

Ported (not re-derived) from Refrance/RZ450e_battery_can_decode_Project/
rx450e_can_analyzer.py's own `trc_write_header`/`trc_format_row` - a
FILEVERSION=1.3 writer confirmed byte-for-byte against a real PCAN-Explorer
v6.8 recording there, so files written here open cleanly in PCAN-Explorer/
PCAN-View too. Per this project's CLAUDE.md convention (port real-hardware-
confirmed formulas verbatim, don't re-derive them by hand).

This project has two logical connections instead of the reference project's
bus1/bus2 split - `rz450e` maps to bus 1, `leaf` maps to bus 2 in the .trc
file, purely a labeling convention for the log format, not a statement about
physical wiring (see docs/02's note on the RZ450e's own two internal logical
buses, which are a separate, unrelated concept).
"""
import re
import threading
import time
from datetime import datetime

TRC_OLE_EPOCH = datetime(1899, 12, 30)
_TRC_BUS_TO_NUM = {'rz450e': 1, 'leaf': 2}
_TRC_NUM_TO_BUS = {1: 'rz450e', 2: 'leaf'}
_TRC_ROW_RE = re.compile(
    r'^\s*\d+\)\s*([\d.]+)\s+(\d+)\s+(Rx|Tx)\s+([0-9A-Fa-f]+)\s+\S+\s+'
    r'(\d+)\s*((?:[0-9A-Fa-f]{2}\s*)*)$')


def _trc_ole_date(dt):
    """datetime -> OLE Automation date (days since 1899-12-30), what PCAN-
    Explorer writes as $STARTTIME."""
    delta = dt - TRC_OLE_EPOCH
    return delta.days + delta.seconds / 86400.0 + delta.microseconds / 86400e6


def _trc_start_time_str(dt):
    return (f'{dt.month}/{dt.day}/{dt.year} {dt.hour}:{dt.minute:02d}:'
            f'{dt.second:02d}.{dt.microsecond // 1000:03d}.0')


def _write_header(fh, start_dt, bitrate):
    kbit = bitrate // 1000
    fh.write(';$FILEVERSION=1.3\n')
    fh.write(f';$STARTTIME={_trc_ole_date(start_dt):.10f}\n')
    fh.write(';\n')
    fh.write(f';   Start time: {_trc_start_time_str(start_dt)}\n')
    fh.write(';   Generated by MiniLeaf Battery Bridge Translator\n')
    fh.write(';-------------------------------------------------------------------------------\n')
    fh.write(';   Bus  Connection   Net Connection    Protocol  Bit rate\n')
    fh.write(f';   1    Connection1  rz450e@pcan_usb   CAN       {kbit} kbit/s\n')
    fh.write(f';   2    Connection2  leaf@pcan_usb     CAN       {kbit} kbit/s\n')
    fh.write(';-------------------------------------------------------------------------------\n')
    fh.write(';   Message   Time    Bus  Type   ID    Reserved\n')
    fh.write(';   Number    Offset  |    |      [hex] |   Data Length Code\n')
    fh.write(';   |         [ms]    |    |      |     |   |    Data [hex] ...\n')
    fh.write(';   |         |       |    |      |     |   |    |\n')
    fh.write(';---+-- ------+------ +- --+-- ---+---- +- -+-- -+ -- -- -- -- -- -- --\n')


def _format_row(n, offset_ms, bus_label, is_tx, can_id, dlc, data):
    """One data row, formatted to the exact fixed-width columns PCAN-Explorer
    uses (see _write_header)."""
    bus_num = _TRC_BUS_TO_NUM.get(bus_label, 0)
    typ = 'Tx' if is_tx else 'Rx'
    id_hex = f'{can_id:04X}'
    data_hex = ' '.join(f'{b:02X}' for b in data)
    return (f'{n:>6})' + f'{offset_ms:>14.3f}' + f' {bus_num}' + f'  {typ:<2}'
            + f'        {id_hex:>4}' + f' -  {dlc}    ' + data_hex + '\n')


def read_trc_rows(path):
    """Parse a .trc log back into dicts with timestamp/bus/dir/can_id_hex/
    dlc/data_hex string keys - not currently used by this project's own GUI,
    included for the same reason the reference project keeps it: a captured
    log is only useful if something can read it back later."""
    start_epoch = 0.0
    with open(path, encoding='utf-8', errors='replace') as fh:
        for line in fh:
            line = line.rstrip('\n')
            if not line.strip():
                continue
            if line.lstrip().startswith(';'):
                m = re.match(r';\$STARTTIME=([\d.eE+-]+)', line.strip())
                if m:
                    from datetime import timedelta
                    start_epoch = (TRC_OLE_EPOCH + timedelta(days=float(m.group(1)))).timestamp()
                continue
            m = _TRC_ROW_RE.match(line)
            if not m:
                continue
            offset_ms, bus_num, typ, id_hex, dlc, data_str = m.groups()
            ts = start_epoch + float(offset_ms) / 1000.0
            yield {
                'timestamp': f'{ts:.6f}',
                'bus': _TRC_NUM_TO_BUS.get(int(bus_num), 'U'),
                'dir': 'TX' if typ == 'Tx' else 'RX',
                'can_id_hex': id_hex,
                'dlc': dlc,
                'data_hex': data_str.strip(),
            }


class TrcLogger:
    """Thread-safe capture session: RX frames are logged from the ingest
    threads (bridge/realtime_engine.py), TX frames from
    bridge/can_backend.py's BusConnection.send() (whichever thread calls
    it) - one lock serializes every write so rows never interleave or
    corrupt mid-line under concurrent RX/TX traffic."""

    def __init__(self):
        self._lock = threading.Lock()
        self._fh = None
        self._msgnum = 0
        self._start_mono = None

    @property
    def active(self):
        with self._lock:
            return self._fh is not None

    def start(self, path, bitrate):
        fh = open(path, 'w', newline='')
        _write_header(fh, datetime.now(), bitrate)
        with self._lock:
            self._fh = fh
            self._msgnum = 0
            self._start_mono = time.monotonic()

    def stop(self):
        with self._lock:
            fh, self._fh = self._fh, None
        if fh:
            fh.close()

    def log_frame(self, bus_label, is_tx, arb_id, dlc, data):
        with self._lock:
            if not self._fh:
                return
            self._msgnum += 1
            offset_ms = (time.monotonic() - self._start_mono) * 1000.0
            self._fh.write(_format_row(self._msgnum, offset_ms, bus_label, is_tx, arb_id, dlc, data))
