/* AUTO-GENERATED by tools/export_stm32_config.py - DO NOT EDIT BY HAND.
 * Source profile: profile (config/profile.json)
 * Generated: 2026-08-20T13:20:24
 * Re-run the script after editing config/profile.json; this file is a
 * compile-time snapshot only - the firmware never reads profile.json or
 * any other runtime config source. See docs/09-stm32-export-format.md.
 */
#ifndef BRIDGE_CONFIG_GEN_H
#define BRIDGE_CONFIG_GEN_H

#include <stdint.h>
#include "leaf_output.h"     /* LeafState - bridge_config_apply_mapping_ties() below */
#include "rz450e_ingest.h"   /* RzState/g_rz_state - bridge_config_apply_mapping_ties() below */

/* ---- Vehicle / pack spec ---- */
#define BRIDGE_CFG_PROFILE_NAME "profile"
#define BRIDGE_CFG_CAR_GEN "ZE1"
#define BRIDGE_CFG_CAR_GEN_IS_ZE1 1
#define BRIDGE_CFG_BATTERY_GEN "ZE1"
#define BRIDGE_CFG_BATTERY_GEN_IS_ZE1 1
#define BRIDGE_CFG_BATTERY_KWH 40
#define BRIDGE_CFG_BATTERY_IS_62KWH 0
#define BRIDGE_CFG_USABLE_CAPACITY_KWH 64.0f
#define BRIDGE_CFG_NAMEPLATE_CAPACITY_AH 201.0f

/* ---- Generated/opaque Leaf-signal send flags (docs/03) ---- */
#define BRIDGE_CFG_SEND_PRUN 1 /* PRUN counter (2-bit, packed into 0x1DB/0x1DC/0x55B/0x1ED) */
#define BRIDGE_CFG_SEND_VOLTAGE_LATCH_TOGGLE 1 /* Voltage latch toggle bit (0x1DB byte 3 bit 0) */
#define BRIDGE_CFG_SEND_HEARTBEAT_1C2 1 /* 0x1C2 heartbeat byte */
#define BRIDGE_CFG_SEND_CODE_1DC 1 /* 0x1DC bytes 4-6 opaque cycle */
#define BRIDGE_CFG_SEND_CHG_TIME_5BC 1 /* 0x5BC bytes 5-7 charge-time cycle */
#define BRIDGE_CFG_SEND_HIST_5C0 1 /* 0x5C0 mux + bytes 3-5 history cycle */
#define BRIDGE_CFG_SEND_SEQ_5EB 1 /* 0x5EB full-frame 45-step cycle (ZE1 only) */

/* ---- Charge emulation (charger-ramp + AC taper + AC temp derate) ---- */
#define BRIDGE_CFG_CE_CHARGE_EMULATE 1 /* Emulate charger request (0x1DC ramp) */
#define BRIDGE_CFG_CE_AC_TAPER_ENABLED 1 /* AC charger overvoltage taper enabled */
#define BRIDGE_CFG_CE_EXTENDED_MODE 0 /* Extended mode active (road trip - charge to extended target) */
#define BRIDGE_CFG_CE_REQUIRE_LIVE_DATA_TO_CHARGE 1 /* Require genuinely live (not cached/default) battery data before the charge ramp can start */
#define BRIDGE_CFG_CE_AC_TEMP_DERATE_ENABLED 1 /* AC charger temperature derate enabled */
#define BRIDGE_CFG_CE_CHARGE_TARGET_KW 92.2f /* Charger ramp target (kW) */
#define BRIDGE_CFG_CE_CHG_UPRATE_LEVEL 7.0f /* Uprate level / ramp rate (0-7) */
#define BRIDGE_CFG_CE_AC_FULL_V 4.13f /* AC charge full power below (V/cell) */
#define BRIDGE_CFG_CE_AC_MIN_V 4.17f /* AC charge minimum power at/above (V/cell) - holds at AC min kW, does not stop charging */
#define BRIDGE_CFG_CE_AC_CUTOFF_V 4.18f /* AC charge stop-charging voltage (V/cell) - ends session (full_charge_flag) */
#define BRIDGE_CFG_CE_AC_EMERGENCY_V 4.2f /* AC charge emergency high V (hard cut) */
#define BRIDGE_CFG_CE_AC_MIN_KW 1.0f /* AC charge minimum power request (kW) */
#define BRIDGE_CFG_CE_AC_MAX_KW 8.0f /* AC charge maximum power request (kW) */
#define BRIDGE_CFG_CE_DC_MIN_KW 5.0f /* DC fast-charge minimum power request (kW) - PLACEHOLDER, not yet wired to any logic */
#define BRIDGE_CFG_CE_DC_MAX_KW 50.0f /* DC fast-charge maximum power request (kW) - PLACEHOLDER, not yet wired to any logic */
#define BRIDGE_CFG_CE_QC_MAX_SOC_PCT 80.0f /* QC (DC fast-charge) max SOC % - GIDS/QC capacity ceiling */
#define BRIDGE_CFG_CE_DAILY_TARGET_PCT 80.0f /* Daily target % (SoC stop point) */
#define BRIDGE_CFG_CE_EXTENDED_TARGET_PCT 95.0f /* Extended target % (SoC stop point) */
#define BRIDGE_CFG_CE_AC_DERATE_LOW_START_C 10.0f /* AC charge cold-derate start °C (coldest probe) */
#define BRIDGE_CFG_CE_AC_LOW_BLOCK_C 0.0f /* AC charge low block °C (coldest probe) */
#define BRIDGE_CFG_CE_AC_DERATE_START_C 40.0f /* AC charge derate start °C (hottest probe) */
#define BRIDGE_CFG_CE_AC_HARD_STOP_C 50.0f /* AC charge hard stop °C (hottest probe) - ends session */

/* ---- Engine timing (DID polling cadence, wind-down/charge heuristics) ---- */
#define BRIDGE_CFG_ET_DID_RESPONSE_TIMEOUT_S 5.0f /* DID response timeout (s) */
#define BRIDGE_CFG_ET_DID_INTER_REQUEST_GAP_S 0.3f /* DID inter-request pacing gap (s) */
#define BRIDGE_CFG_ET_DID_TEMP_POLL_INTERVAL_S 2.0f /* Temp probe (DID 0x1814) poll interval (s) */
#define BRIDGE_CFG_ET_DID_TEMP_FRESH_WINDOW_S 20.0f /* Temp probe (DID 0x1814) freshness window (s) */
#define BRIDGE_CFG_ET_IGNITION_QUIET_S 0.5f /* Ignition-signal quiet window (s) */
#define BRIDGE_CFG_ET_IGNITION_OFF_DELAY_S 10.0f /* Ignition-off wind-down delay (s) */
#define BRIDGE_CFG_ET_IGNITION_GRACE_S 10.0f /* Ignition-off grace period after startup (s) */
#define BRIDGE_CFG_ET_CHG_END_STOP_S 3.0f /* Charge-session-end wind-down delay / replug-debounce gap (s) */
#define BRIDGE_CFG_ET_CHG_STALL_TIMEOUT_S 15.0f /* Charge-stall wind-down timeout (s) */
#define BRIDGE_CFG_ET_CHG_CMD_FRESH_S 0.5f /* 0x1F2 charge-command freshness window (s) */
#define BRIDGE_CFG_ET_BUS_SILENCE_TIMEOUT_S 30.0f /* Leaf-bus total silence wind-down timeout (s) */
/* Firmware-only, not part of config/profile.json - see STM32_ONLY_ENGINE_TIMING_DEFAULTS
 * in tools/export_stm32_config.py for why. */
#define BRIDGE_CFG_ET_SLEEP_IDLE_TIMEOUT_S 60.0f /* Idle timeout before entering CAN-bus-silence sleep (s) - STM32 firmware only */

/* ---- Management/safety features (docs/05) - thresholds only, algorithm shapes hardcoded ---- */
/* -- low_voltage_cutoff -- */
#define BRIDGE_CFG_MF_LOW_VOLTAGE_CUTOFF_ENABLED 1
#define BRIDGE_CFG_MF_LOW_VOLTAGE_CUTOFF_MIN_CELL_V 3.2f
#define BRIDGE_CFG_MF_LOW_VOLTAGE_CUTOFF_MIN_SOC_PCT 3.0f
#define BRIDGE_CFG_MF_LOW_VOLTAGE_CUTOFF_EMERGENCY_LOW_V 2.8f
#define BRIDGE_CFG_MF_LOW_VOLTAGE_CUTOFF_SOFT_CUT_PERSISTENCE_S 2.0f
/* -- discharge_power_taper -- */
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_ENABLED 1
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_TAPER_START_V 3.3f
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_TAPER_MIN_V 3.0f
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_TAPER_START_SOC_PCT 15.0f
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_TAPER_MIN_SOC_PCT 5.0f
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_RECOVERY_RAMP_S 3.0f
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_DISCHARGE_MIN_KW 3.0f
#define BRIDGE_CFG_MF_DISCHARGE_POWER_TAPER_DISCHARGE_MAX_KW 110.0f
/* -- charge_target_taper -- */
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_ENABLED 1
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_REGEN_FULL_V 4.05f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_REGEN_MIN_V 4.1f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_EMERGENCY_HIGH_V 4.2f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_RECOVERY_RAMP_S 3.0f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_REGEN_MIN_KW 0.0f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_REGEN_MAX_KW 70.0f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_REGEN_FULL_SOC_PCT 90.0f
#define BRIDGE_CFG_MF_CHARGE_TARGET_TAPER_REGEN_MIN_SOC_PCT 95.0f
/* -- over_temperature_derate -- */
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_ENABLED 1
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_CHARGE_DERATE_LOW_START_C 10.0f
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_CHARGE_LOW_BLOCK_C 0.0f
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_CHARGE_DERATE_START_C 32.2f
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_CHARGE_HARD_STOP_C 45.0f
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_DISCHARGE_DERATE_START_C 55.0f
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_DISCHARGE_HARD_STOP_C 60.0f
#define BRIDGE_CFG_MF_OVER_TEMPERATURE_DERATE_EMERGENCY_TEMP_C 61.0f
/* -- cell_imbalance_monitor -- */
#define BRIDGE_CFG_MF_CELL_IMBALANCE_MONITOR_ENABLED 1
#define BRIDGE_CFG_MF_CELL_IMBALANCE_MONITOR_WARN_DELTA_V 0.15f
/* -- overcurrent_monitor -- */
#define BRIDGE_CFG_MF_OVERCURRENT_MONITOR_ENABLED 1
#define BRIDGE_CFG_MF_OVERCURRENT_MONITOR_CONTINUOUS_DISCHARGE_WARN_A 150.0f
#define BRIDGE_CFG_MF_OVERCURRENT_MONITOR_CONTINUOUS_CHARGE_WARN_A 30.0f
#define BRIDGE_CFG_MF_OVERCURRENT_MONITOR_PERSISTENCE_S 5.0f
/* -- staleness_watchdog -- */
#define BRIDGE_CFG_MF_STALENESS_WATCHDOG_ENABLED 1
#define BRIDGE_CFG_MF_STALENESS_WATCHDOG_SOFT_CUT_S 60.0f
#define BRIDGE_CFG_MF_STALENESS_WATCHDOG_HARD_ESCALATION_S 5.0f
/* -- cell_data_cross_check -- */
#define BRIDGE_CFG_MF_CELL_DATA_CROSS_CHECK_ENABLED 1
#define BRIDGE_CFG_MF_CELL_DATA_CROSS_CHECK_MAX_DELTA_V 0.25f
#define BRIDGE_CFG_MF_CELL_DATA_CROSS_CHECK_SOFT_CUT_S 60.0f
#define BRIDGE_CFG_MF_CELL_DATA_CROSS_CHECK_HARD_ESCALATION_S 5.0f
/* -- temp_data_cross_check -- */
#define BRIDGE_CFG_MF_TEMP_DATA_CROSS_CHECK_ENABLED 1
#define BRIDGE_CFG_MF_TEMP_DATA_CROSS_CHECK_MAX_DELTA_C 5.555555555555555f
#define BRIDGE_CFG_MF_TEMP_DATA_CROSS_CHECK_SOFT_CUT_S 60.0f
#define BRIDGE_CFG_MF_TEMP_DATA_CROSS_CHECK_HARD_ESCALATION_S 5.0f
/* -- temp_probe_cross_check -- */
#define BRIDGE_CFG_MF_TEMP_PROBE_CROSS_CHECK_ENABLED 1
#define BRIDGE_CFG_MF_TEMP_PROBE_CROSS_CHECK_MAX_DELTA_C 2.0f
#define BRIDGE_CFG_MF_TEMP_PROBE_CROSS_CHECK_SOFT_CUT_S 60.0f
#define BRIDGE_CFG_MF_TEMP_PROBE_CROSS_CHECK_HARD_ESCALATION_S 5.0f
/* -- input_validation -- */
#define BRIDGE_CFG_MF_INPUT_VALIDATION_ENABLED 1
/* -- checksum_validation -- */
#define BRIDGE_CFG_MF_CHECKSUM_VALIDATION_ENABLED 1

/* ---- Signal mapping ties (bridge/mapping_engine.py) - codegen-emitted directly, no runtime interpreter ---- */
/* Applies every configured mapping tie - see _emit_tie_statement() in
 * tools/export_stm32_config.py for why this is generated straight-line C
 * instead of a runtime-interpreted table. `static` and only ever called
 * from mapping_engine.c - every other firmware file includes this header
 * too but never calls this function, so it costs them nothing (an
 * unreferenced `static` function is eliminated per translation unit). `inline`
 * is what it is here for, not for the optimizer: Clang/GCC do not emit
 * -Wunused-function for an unused `static inline` (unlike a plain `static`,
 * which warns in every one of the 5 TUs that never call it) - silences the
 * warning with zero behavior/size change, since a header-defined helper not
 * called by every including file is exactly what `inline` signals. */
static inline void bridge_config_apply_mapping_ties(LeafState *out)
{
    /* pack_v -> pack_voltage_v */
    if (g_rz_state.pack_v.last_update_tick != 0) { out->pack_voltage_v = g_rz_state.pack_v.value * 1.0f + 0.0f; }
    /* current -> pack_current_a (SIGN INVERTED: RZ450e +discharge -> Leaf +charge) */
    if (g_rz_state.current.last_update_tick != 0) { out->pack_current_a = g_rz_state.current.value * -1.0f + 0.0f; }
    /* soc_pct -> usable_soc */
    if (g_rz_state.soc_pct.last_update_tick != 0) { out->usable_soc = g_rz_state.soc_pct.value * 1.0f + 0.0f; }
    /* soc_pct -> fine_soc_pct */
    if (g_rz_state.soc_pct.last_update_tick != 0) { out->fine_soc_pct = g_rz_state.soc_pct.value * 1.0f + 0.0f; }
    /* soc_pct -> soc_correction (dash SOC% display, confirmed 2 raw counts/%) */
    if (g_rz_state.soc_pct.last_update_tick != 0) { out->soc_correction = g_rz_state.soc_pct.value * 2.0f + 0.0f; }
    /* capacity_pack1_ah -> capacity_bars_raw (confirmed 0-200Ah = 0-14 bars) */
    if (g_rz_state.capacity_pack1_ah.last_update_tick != 0) { out->capacity_bars_raw = g_rz_state.capacity_pack1_ah.value * 0.07f + 0.0f; }
    /* temp_max (°C) -> batt_temp_c (°C) (identity - both already °C as of 2026-08-09) */
    if (g_rz_state.temp_max.last_update_tick != 0) { out->batt_temp_c = g_rz_state.temp_max.value * 1.0f + 0.0f; }
    /* capacity_pack1_ah -> soh_pct */
    if (g_rz_state.capacity_pack1_ah.last_update_tick != 0) { out->soh_pct = (g_rz_state.capacity_pack1_ah.value / 201.0f) * 100.0f; }
    /* temp_max -> temp_segment_pct (PROVISIONAL, not hardware-confirmed - see docs/10) */
    if (g_rz_state.temp_max.last_update_tick != 0) { out->temp_segment_pct = g_rz_state.temp_max.value * 1.6666666666666667f + 0.0f; }
}

/* ---- Real-Leaf protocol timing (bit-verified, not user-configurable) ---- */
#define BRIDGE_PROTO_TX_PERIOD_MS_1DB 10
#define BRIDGE_PROTO_TX_PERIOD_MS_1DC 10
#define BRIDGE_PROTO_TX_PERIOD_MS_1C2 10
#define BRIDGE_PROTO_TX_PERIOD_MS_1ED 10
#define BRIDGE_PROTO_TX_PERIOD_MS_55B 100
#define BRIDGE_PROTO_TX_PERIOD_MS_5BC 100
#define BRIDGE_PROTO_TX_PERIOD_MS_59E 500
#define BRIDGE_PROTO_TX_PERIOD_MS_5C0 500
#define BRIDGE_PROTO_TX_PERIOD_MS_5EB 500
#define BRIDGE_PROTO_T_1DB_START 65
#define BRIDGE_PROTO_T_55B_START 155
#define BRIDGE_PROTO_T_59E_START 565
#define BRIDGE_PROTO_T_PH_B 195
#define BRIDGE_PROTO_T_PH_C 325
#define BRIDGE_PROTO_T_VALID 865
#define BRIDGE_PROTO_T_RUNNING 2105
#define BRIDGE_PROTO_PWRDOWN_STAGE2_MS 250
#define BRIDGE_PROTO_PWRDOWN_STAGE3_MS 300
#define BRIDGE_PROTO_PWRDOWN_STAGE4_MS 1200
#define BRIDGE_PROTO_PWRDOWN_DEFAULT_COOLDOWN_S 1.0f
#define BRIDGE_PROTO_CHG_CMD_IDLE 100
#define BRIDGE_PROTO_IGNITION_ID_COUNT 3
static const uint16_t BRIDGE_PROTO_IGNITION_IDS[BRIDGE_PROTO_IGNITION_ID_COUNT] = { 0x108u, 0x1CBu, 0x284u };

/* ---- Leaf output DEFAULTS/RANGES (bridge/leaf_signals.py) ---- */
#define BRIDGE_PROTO_DEFAULT_PACK_VOLTAGE_V 378.5f
#define BRIDGE_PROTO_RANGE_PACK_VOLTAGE_V_LO 0.0f
#define BRIDGE_PROTO_RANGE_PACK_VOLTAGE_V_HI 450.0f
#define BRIDGE_PROTO_DEFAULT_PACK_CURRENT_A 0.0f
#define BRIDGE_PROTO_RANGE_PACK_CURRENT_A_LO -400.0f
#define BRIDGE_PROTO_RANGE_PACK_CURRENT_A_HI 200.0f
#define BRIDGE_PROTO_DEFAULT_USABLE_SOC 45.0f
#define BRIDGE_PROTO_RANGE_USABLE_SOC_LO 0.0f
#define BRIDGE_PROTO_RANGE_USABLE_SOC_HI 100.0f
#define BRIDGE_PROTO_DEFAULT_FAILSAFE_STATUS 0.0f
#define BRIDGE_PROTO_RANGE_FAILSAFE_STATUS_LO 0.0f
#define BRIDGE_PROTO_RANGE_FAILSAFE_STATUS_HI 7.0f
#define BRIDGE_PROTO_DEFAULT_RELAY_CUT_REQUEST 0.0f
#define BRIDGE_PROTO_RANGE_RELAY_CUT_REQUEST_LO 0.0f
#define BRIDGE_PROTO_RANGE_RELAY_CUT_REQUEST_HI 3.0f
#define BRIDGE_PROTO_DEFAULT_DISCHARGE_PWR_STS 1.0f
#define BRIDGE_PROTO_RANGE_DISCHARGE_PWR_STS_LO 0.0f
#define BRIDGE_PROTO_RANGE_DISCHARGE_PWR_STS_HI 3.0f
#define BRIDGE_PROTO_DEFAULT_DISCHARGE_LIMIT_KW 110.0f
#define BRIDGE_PROTO_RANGE_DISCHARGE_LIMIT_KW_LO 0.0f
#define BRIDGE_PROTO_RANGE_DISCHARGE_LIMIT_KW_HI 255.75f
#define BRIDGE_PROTO_DEFAULT_CHARGE_LIMIT_KW 70.0f
#define BRIDGE_PROTO_RANGE_CHARGE_LIMIT_KW_LO 0.0f
#define BRIDGE_PROTO_RANGE_CHARGE_LIMIT_KW_HI 255.75f
#define BRIDGE_PROTO_DEFAULT_CHARGER_LIMIT_KW 92.3f
#define BRIDGE_PROTO_RANGE_CHARGER_LIMIT_KW_LO -10.0f
#define BRIDGE_PROTO_RANGE_CHARGER_LIMIT_KW_HI 92.3f
#define BRIDGE_PROTO_DEFAULT_CHARGE_PWR_STS 1.0f
#define BRIDGE_PROTO_RANGE_CHARGE_PWR_STS_LO 0.0f
#define BRIDGE_PROTO_RANGE_CHARGE_PWR_STS_HI 3.0f
#define BRIDGE_PROTO_DEFAULT_FINE_SOC_PCT 46.3f
#define BRIDGE_PROTO_RANGE_FINE_SOC_PCT_LO 0.0f
#define BRIDGE_PROTO_RANGE_FINE_SOC_PCT_HI 102.3f
#define BRIDGE_PROTO_DEFAULT_SOH_PCT 100.0f
#define BRIDGE_PROTO_RANGE_SOH_PCT_LO 0.0f
#define BRIDGE_PROTO_RANGE_SOH_PCT_HI 127.0f
#define BRIDGE_PROTO_DEFAULT_GIDS 120.0f
#define BRIDGE_PROTO_RANGE_GIDS_LO 0.0f
#define BRIDGE_PROTO_RANGE_GIDS_HI 1023.0f
#define BRIDGE_PROTO_DEFAULT_CAPACITY_BARS_RAW 6.0f
#define BRIDGE_PROTO_RANGE_CAPACITY_BARS_RAW_LO 0.0f
#define BRIDGE_PROTO_RANGE_CAPACITY_BARS_RAW_HI 15.0f
#define BRIDGE_PROTO_DEFAULT_PWR_LIMIT_REASON 0.0f
#define BRIDGE_PROTO_RANGE_PWR_LIMIT_REASON_LO 0.0f
#define BRIDGE_PROTO_RANGE_PWR_LIMIT_REASON_HI 7.0f
#define BRIDGE_PROTO_DEFAULT_TEMP_SEGMENT_PCT 58.3f
#define BRIDGE_PROTO_RANGE_TEMP_SEGMENT_PCT_LO 0.0f
#define BRIDGE_PROTO_RANGE_TEMP_SEGMENT_PCT_HI 100.0f
#define BRIDGE_PROTO_DEFAULT_QC_FULL_WH 23000.0f
#define BRIDGE_PROTO_RANGE_QC_FULL_WH_LO 0.0f
#define BRIDGE_PROTO_RANGE_QC_FULL_WH_HI 51100.0f
#define BRIDGE_PROTO_DEFAULT_QC_REMAIN_WH 10500.0f
#define BRIDGE_PROTO_RANGE_QC_REMAIN_WH_LO 0.0f
#define BRIDGE_PROTO_RANGE_QC_REMAIN_WH_HI 51100.0f
#define BRIDGE_PROTO_DEFAULT_SOC_CORRECTION 90.0f
#define BRIDGE_PROTO_RANGE_SOC_CORRECTION_LO 0.0f
#define BRIDGE_PROTO_RANGE_SOC_CORRECTION_HI 200.0f
#define BRIDGE_PROTO_DEFAULT_BATT_TEMP_C 37.0f
#define BRIDGE_PROTO_RANGE_BATT_TEMP_C_LO -40.0f
#define BRIDGE_PROTO_RANGE_BATT_TEMP_C_HI 86.0f
#define BRIDGE_PROTO_DEFAULT_DTC 0.0f
#define BRIDGE_PROTO_RANGE_DTC_LO 0.0f
#define BRIDGE_PROTO_RANGE_DTC_HI 255.0f
#define BRIDGE_PROTO_DEFAULT_MAIN_RELAY_ON 1.0f
#define BRIDGE_PROTO_RANGE_MAIN_RELAY_ON_LO 0.0f
#define BRIDGE_PROTO_RANGE_MAIN_RELAY_ON_HI 1.0f
#define BRIDGE_PROTO_DEFAULT_INTERLOCK 1.0f
#define BRIDGE_PROTO_RANGE_INTERLOCK_LO 0.0f
#define BRIDGE_PROTO_RANGE_INTERLOCK_HI 1.0f
#define BRIDGE_PROTO_DEFAULT_FULL_CHARGE_FLAG 0.0f
#define BRIDGE_PROTO_RANGE_FULL_CHARGE_FLAG_LO 0.0f
#define BRIDGE_PROTO_RANGE_FULL_CHARGE_FLAG_HI 1.0f
#define BRIDGE_PROTO_DEFAULT_IR_MALFUNCTION 0.0f
#define BRIDGE_PROTO_RANGE_IR_MALFUNCTION_LO 0.0f
#define BRIDGE_PROTO_RANGE_IR_MALFUNCTION_HI 1.0f
#define BRIDGE_PROTO_DEFAULT_CAPACITY_EMPTY 0.0f
#define BRIDGE_PROTO_RANGE_CAPACITY_EMPTY_LO 0.0f
#define BRIDGE_PROTO_RANGE_CAPACITY_EMPTY_HI 1.0f
#define BRIDGE_PROTO_DEFAULT_CHG2_LIMIT_KW 10.0f
#define BRIDGE_PROTO_RANGE_CHG2_LIMIT_KW_LO 10.0f
#define BRIDGE_PROTO_RANGE_CHG2_LIMIT_KW_HI 204.0f

/* ---- Opaque generated-signal replay tables (bridge/leaf_signals.py) ---- */
#define BRIDGE_PROTO_CODE_1DC_COUNT 4
static const uint8_t BRIDGE_PROTO_CODE_1DC[BRIDGE_PROTO_CODE_1DC_COUNT][3] = {
    { 0x0Cu, 0xD8u, 0xE4u },
    { 0x01u, 0x14u, 0xD4u },
    { 0x04u, 0xE0u, 0xC8u },
    { 0x08u, 0xC0u, 0xC0u },
};
#define BRIDGE_PROTO_CHG_TIME_5BC_COUNT 7
static const uint8_t BRIDGE_PROTO_CHG_TIME_5BC[BRIDGE_PROTO_CHG_TIME_5BC_COUNT][3] = {
    { 0x00u, 0x1Fu, 0xFFu },
    { 0x00u, 0xA0u, 0x67u },
    { 0x01u, 0x00u, 0xE9u },
    { 0x01u, 0x61u, 0x7Au },
    { 0x02u, 0x40u, 0x33u },
    { 0x02u, 0xA0u, 0x74u },
    { 0x03u, 0x00u, 0xBFu },
};
#define BRIDGE_PROTO_HIST5C0_COUNT 6
/* indexed [mux-1] - mux is 1..6, matching bridge/leaf_signals.py's HIST5C0 dict keys */
static const uint8_t BRIDGE_PROTO_HIST5C0[BRIDGE_PROTO_HIST5C0_COUNT][3] = {
    { 0x00u, 0x20u, 0xC8u },
    { 0x00u, 0x00u, 0xC4u },
    { 0x00u, 0x00u, 0x00u },
    { 0x00u, 0x00u, 0x94u },
    { 0x00u, 0x00u, 0x7Cu },
    { 0x01u, 0xC8u, 0x6Cu },
};
#define BRIDGE_PROTO_SEQ_5EB_COUNT 45
static const uint8_t BRIDGE_PROTO_SEQ_5EB[BRIDGE_PROTO_SEQ_5EB_COUNT][8] = {
    { 0x26u, 0x01u, 0x00u, 0x01u, 0x07u, 0x0Eu, 0xC0u, 0x33u },
    { 0x26u, 0x11u, 0x00u, 0x01u, 0x07u, 0x0Eu, 0xC0u, 0x3Bu },
    { 0x26u, 0x20u, 0x3Du, 0x3Eu, 0x3Du, 0x21u, 0x40u, 0x00u },
    { 0x26u, 0x30u, 0x3Du, 0x3Eu, 0x3Du, 0x21u, 0x40u, 0x4Du },
    { 0x26u, 0x42u, 0x7Du, 0x7Eu, 0x7Du, 0x3Bu, 0x80u, 0x00u },
    { 0x26u, 0x50u, 0x00u, 0x12u, 0x48u, 0x00u, 0x00u, 0x00u },
    { 0x26u, 0x60u, 0x7Du, 0x7Eu, 0x7Du, 0x00u, 0x00u, 0x00u },
    { 0x26u, 0x70u, 0x0Fu, 0x31u, 0x23u, 0x08u, 0xC0u, 0x23u },
    { 0x26u, 0x80u, 0x3Eu, 0x3Eu, 0x3Du, 0x00u, 0x00u, 0x00u },
    { 0x46u, 0x01u, 0x00u, 0x01u, 0x07u, 0x0Eu, 0xC0u, 0x33u },
    { 0x46u, 0x11u, 0x00u, 0x01u, 0x08u, 0x00u, 0x00u, 0x0Au },
    { 0x46u, 0x20u, 0x3Du, 0x3Eu, 0x3Du, 0x21u, 0x40u, 0x00u },
    { 0x46u, 0x30u, 0x3Du, 0x3Eu, 0x3Du, 0x21u, 0x40u, 0x3Bu },
    { 0x46u, 0x42u, 0x7Du, 0x7Eu, 0x7Du, 0x3Bu, 0x80u, 0x00u },
    { 0x46u, 0x50u, 0x00u, 0x12u, 0x48u, 0x00u, 0x00u, 0x00u },
    { 0x46u, 0x60u, 0x7Du, 0x7Fu, 0x7Cu, 0x00u, 0x00u, 0x00u },
    { 0x46u, 0x70u, 0x4Au, 0x4Fu, 0x23u, 0x08u, 0xC0u, 0x23u },
    { 0x46u, 0x80u, 0x3Eu, 0x3Eu, 0x3Du, 0x00u, 0x00u, 0x00u },
    { 0x66u, 0x02u, 0x00u, 0x0Du, 0x13u, 0x00u, 0x80u, 0x16u },
    { 0x66u, 0x12u, 0x00u, 0x0Du, 0x13u, 0x0Eu, 0x40u, 0x30u },
    { 0x66u, 0x20u, 0x3Fu, 0x40u, 0x3Fu, 0x14u, 0x40u, 0x00u },
    { 0x66u, 0x30u, 0x55u, 0x57u, 0x54u, 0x76u, 0x01u, 0x49u },
    { 0x66u, 0x42u, 0x75u, 0x76u, 0x75u, 0x7Cu, 0x00u, 0x00u },
    { 0x66u, 0x50u, 0x50u, 0x01u, 0x13u, 0x00u, 0x00u, 0x00u },
    { 0x66u, 0x60u, 0xEAu, 0xECu, 0xE9u, 0x00u, 0x00u, 0x00u },
    { 0x66u, 0x70u, 0x01u, 0x4Fu, 0x5Eu, 0x10u, 0x80u, 0x18u },
    { 0x66u, 0x80u, 0x50u, 0x57u, 0x3Fu, 0x00u, 0x00u, 0x00u },
    { 0x86u, 0x02u, 0x00u, 0x11u, 0x09u, 0x04u, 0x40u, 0x37u },
    { 0x86u, 0x12u, 0x00u, 0x11u, 0x0Cu, 0x0Du, 0x80u, 0x32u },
    { 0x86u, 0x20u, 0x44u, 0x46u, 0x43u, 0x37u, 0x00u, 0x00u },
    { 0x86u, 0x30u, 0x46u, 0x47u, 0x45u, 0x44u, 0xC0u, 0x0Bu },
    { 0x86u, 0x40u, 0x88u, 0x89u, 0x88u, 0x03u, 0x40u, 0x00u },
    { 0x86u, 0x50u, 0x0Bu, 0x10u, 0x11u, 0x00u, 0x00u, 0x00u },
    { 0x86u, 0x60u, 0x9Du, 0x9Eu, 0x9Bu, 0x00u, 0x00u, 0x00u },
    { 0x86u, 0x70u, 0x19u, 0x06u, 0x3Bu, 0x0Du, 0x80u, 0x31u },
    { 0x86u, 0x80u, 0x46u, 0x47u, 0x43u, 0x00u, 0x00u, 0x00u },
    { 0xA6u, 0x02u, 0x00u, 0x11u, 0x0Fu, 0x06u, 0x80u, 0x0Cu },
    { 0xA6u, 0x12u, 0x00u, 0x12u, 0x07u, 0x0Du, 0xC0u, 0x11u },
    { 0xA6u, 0x20u, 0x4Au, 0x4Au, 0x4Au, 0x32u, 0x00u, 0x00u },
    { 0xA6u, 0x30u, 0x48u, 0x49u, 0x47u, 0x6Fu, 0x00u, 0x0Bu },
    { 0xA6u, 0x40u, 0x85u, 0x86u, 0x84u, 0x03u, 0x40u, 0x00u },
    { 0xA6u, 0x50u, 0x31u, 0x02u, 0x03u, 0x00u, 0x00u, 0x00u },
    { 0xA6u, 0x60u, 0xDDu, 0xDFu, 0xDBu, 0x00u, 0x00u, 0x00u },
    { 0xA6u, 0x70u, 0x3Eu, 0x47u, 0x59u, 0x11u, 0x00u, 0x2Eu },
    { 0xA6u, 0x80u, 0x4Au, 0x4Cu, 0x47u, 0x00u, 0x00u, 0x00u },
};

#endif /* BRIDGE_CONFIG_GEN_H */
